apiVersion: v1
kind: Pod
metadata:
  name: mongodb-nfs
spec:
  volumes:
  - name: nfs-test
    persistentVolumeClaim:
      claimName: nfs-pvc
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: nfs-test
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
